name: Automatically run tf plan and comment on PR
on: 
  pull_request:
    types: [opened, reopened, synchronize]
  
jobs:
  auto-plan-the-tf:
    runs-on: [self-hosted, ubuntu-20.04]

    environment: 'Dev'
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ENVIRONMENT: 'public'
      TF_IN_AUTOMATION: 'true' 
    
    defaults:
      run:
        shell: bash
        working-directory: ./dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ~>0.15.0
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var="pagerduty_token=${{secrets.PAGERDUTY_TOKEN}}" -var="windows_machine=false" -var="prod_subscription_id=${{secrets.PROD_SUBSCRIPTION_ID}}"
        continue-on-error: true
      - name: 'Terraform Comment'
        uses: actions/github-script@v4
        env:
          PLAN: "\n```\n${{ steps.plan.outputs.stdout }}\n```\n"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            ${process.env.PLAN}
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1