name: Auto Apply main branch to Dev on PR Merge
on: 
  pull_request:
    types: [closed]

jobs:
  auto-apply-tf:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    
    runs-on: [self-hosted, ubuntu-20.04]

    environment: 'Dev'
    env: 
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ENVIRONMENT: 'public'
      TF_IN_AUTOMATION: 'true'  
    
    defaults:
      run:
        shell: bash
        working-directory: ./dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ~>0.15.0
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="pagerduty_token=${{secrets.PAGERDUTY_TOKEN}}" -var="windows_machine=false" -var="prod_subscription_id=${{secrets.PROD_SUBSCRIPTION_ID}}"